// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cnhhusxhcxjhizzzxorm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNuaGh1c3hoY3hqaGl6enp4b3JtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMxMDUyMzQsImV4cCI6MjA2ODY4MTIzNH0.9Qix5Z5u7D71WRcjU59q3cUlrl0JjhY_B5Z6ju_oEAw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});